name: shell commands

on: [push]

jobs:
    run-shell-commands
    runs-on: ubuntu-latest
    steps:
        -name: checkout
            uses: actions/checkout@v3
        -name: update
            uses: sudo apt update
        -name: multiline script
            run: |
            sudo apt install python3-dev python3-pip python3-virtualenv sqlitebrowser
            sudo pip install -r requirements.txt
        -name: build artifact
            run: python3 manage.py migrate
        -name: migrate
            run: python3 manage.py runserver   
